name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run --if-present build
    - run: pnpm test --experimental-test-coverage --test-coverage-exclude='**/*.test.js' --test-coverage-exclude='test-setup.js' --test-reporter=spec --test-reporter=spec --test-reporter-destination=stdout --test-reporter-destination=coverage.txt
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        node -e 'r=fs.readFileSync("./coverage.txt", "utf8").toString().replace(/\x1b\[[0-?]*[ -/]*[@-~]/g, "").match(/all files\s+[^\d]+(\d{0,3}\.\d{0,2})/)[1] + "%";fetch("https://img.shields.io/badge/coverage-"+"X".repeat(r.length)+"-blue").then(r => r.text()).then(t => fs.writeFileSync("./coverage.svg", t.replace(new RegExp("X".repeat(r.length), "g"), r)))'
        rm -rf ./coverage.txt
        git add .
        git stash
        git checkout _meta
        git stash pop
        git add .
        git commit -m 'Update metadata'
        git push origin _meta
